#!/usr/bin/env python3
"""
OpenGEO -- length-ladder probe for ROADMAP item 11.

The tactic pilot (results/probes/2026-09-19-tactic-pilot.md) found four fact-preserving
tactics moving nothing on three screened targets, at per-cell movement indistinguishable
from resampling noise. One explanation would rescue item 11 and one would end it, and the
pilot cannot tell them apart:

  A. the tactics do not work at the synthesis stage, full stop
  B. the targets were 28-55 words, and within a document that short there is no
     "first" worth moving an answer to -- the model reads the whole thing either way

This probe tests B directly, as a dose-response on target length rather than a single
longer version, which is the idiom H7 used for padding. The target appears at three
nested lengths and each length is run with and without `answer_first`:

    short   27-60 words      the pilot's regime
    mid    114-172 words
    long   215-236 words

If B is right, the `answer_first` effect grows with length. If the effect is flat at zero
across a 4-8x range of document length, B is dead and A is the surviving explanation --
which makes item 11's ranked table unobtainable in Tier 1, because Tier 1 holds retrieval
constant and presentation's causal path plausibly runs through retrieval.

## Why these three questions

Nesting has to be clean: the answer must be present at **every** rung, or a longer rung is
also a document that answers better, and H4 (+0.48 for facts over no facts) swamps the
comparison. That requires a source page whose answer sits in one block with same-topic
prose extending away from it. Two of the pilot's three questions qualify; the third is
kept deliberately as a contrast.

  home_smokealarm   blocks 21-22 / 18-22 / 15-22    answer LAST at every rung
  home_radon        blocks 64 / 62-64 / 58-64       answer LAST at every rung
  finance_housingshare  231-232 / 231-236 / 231-238 answer at sentence 2, FIXED

The first two deepen the buried lede as the document grows -- the answer moves further
from the top in absolute terms. The third grows the document while the answer stays at
sentence two. If `answer_first` responds to length on the first two and not the third,
the mechanism is burial depth. If it responds on all three, it is document length itself.
If it responds on none, neither.

`home_radon` replaces `health_bloodpressure` from the pilot, whose page cannot be extended
without pulling in the blood-pressure category table -- that adds the staging thresholds,
which is added facts, not added length.

## Construction

Every rung is sliced verbatim from the committed snapshot by `sources.py:span()` with
`multi_block=True`, so a rung is a contiguous run of the real page. `answer_first` is not
written by hand: it is generated by moving the answer sentence to the front and asserting
the result is a **pure permutation of the control's words**, so the arm cannot smuggle in
an edit. Candidates are imported unchanged and carry their control text under every
condition; only the target varies.

    python3 corpus/build_corpus_lengthladder.py
"""
import hashlib
import json
import pathlib
import re
import sys

HERE = pathlib.Path(__file__).parent
sys.path.insert(0, str(HERE))
sys.path.insert(0, str(HERE.parent))
import sources as S  # noqa: E402

RUNGS = ["short", "mid", "long"]
CONDITIONS = [f"{r}_{a}" for r in RUNGS for a in ("control", "first")]

# question -> (screen corpus, target key, answer sentence, {rung: (start, end)})
LADDER = {
    "home_smokealarm": (
        "corpus_rankable_screen_b6.json", "cpsc_blog",
        "Check your alarms monthly. Change the batteries yearly.",
        {"short": ("What should you do to protect your family?",
                   "Practice a fire escape plan."),
         "mid": ("CPSC estimates that in 2016", "Practice a fire escape plan."),
         "long": ("Consumers will turn their clocks back one hour",
                  "Practice a fire escape plan.")},
    ),
    "home_radon": (
        "corpus_rankable_screen_b8.json", "epa_radtown",
        "Take action to lower your exposure to radon when at home testing shows "
        "elevated radon levels at or above 4 pCi/L.",
        {"short": ("Take action to lower your exposure to radon",
                   "about getting the problem fixed."),
         "mid": ("There are steps you can take to find radon",
                 "about getting the problem fixed."),
         "long": ("Nearly one in 15 homes in the United States",
                  "about getting the problem fixed.")},
    ),
    "finance_housingshare": (
        "corpus_rankable_screen_b1.json", "census_story22",
        "Households are considered cost burdened when they spend more than 30% of "
        "their income on rent, mortgage and other housing needs.",
        {"short": ("Over 19 million U.S. renter households",
                   "rent, mortgage and other housing needs."),
         "mid": ("Over 19 million U.S. renter households",
                 "were excluded from calculations."),
         "long": ("Over 19 million U.S. renter households",
                  "lived in these 239 counties.")},
    ),
}


def answer_first(text, answer):
    """Move `answer` to the front. Asserts the result is a permutation of the control's
    words -- an authored rewrite that changes a word would fail here rather than ship."""
    answer = S.norm(answer)
    if text.count(answer) != 1:
        raise ValueError(f"answer sentence appears {text.count(answer)} times, need 1: "
                         f"{answer[:60]!r}")
    rest = re.sub(r"\s+", " ", text.replace(answer, " ")).strip()
    out = f"{answer} {rest}".strip()
    if sorted(out.split()) != sorted(text.split()):
        raise AssertionError("answer_first is not a pure permutation of the control")
    return out


def main():
    documents, prompts, report = [], [], []
    for pid, (fname, tkey, answer, rungs) in LADDER.items():
        src = json.load(open(HERE / fname))
        byid = {d["doc_id"]: d for d in src["documents"]}
        prompt = next(p for p in src["prompts"] if p["prompt_id"] == pid)
        tid = f"{pid}__{tkey}"
        url = byid[tid]["source"]["url"]

        variants, words = {}, {}
        prev = None
        for rung in RUNGS:
            start, end = rungs[rung]
            ctl = S.span(url, start, end, multi_block=True)
            ok, missing = S.verbatim(ctl, S.load(url)["text"])
            if not ok:
                raise AssertionError(f"{tid} {rung}: not verbatim -- {missing[:1]}")
            if prev is not None and prev not in ctl:
                raise AssertionError(f"{tid}: {rung} does not contain the shorter rung; "
                                     "the ladder must be nested")
            if S.norm(answer) not in ctl:
                raise AssertionError(f"{tid} {rung}: answer sentence absent -- a rung "
                                     "that lacks the answer confounds length with facts")
            variants[f"{rung}_control"] = ctl
            variants[f"{rung}_first"] = answer_first(ctl, answer)
            words[rung] = len(ctl.split())
            prev = ctl

        pos = {r: variants[f"{r}_control"].split().index(S.norm(answer).split()[0])
               for r in RUNGS}
        report.append((pid, tkey, words, pos))

        for did in prompt["doc_ids"]:
            d = dict(byid[did])
            d["is_target"] = (did == tid)
            if did == tid:
                d["variants"] = variants
                d["variant_provenance"] = {
                    **{f"{r}_control": f"verbatim span of the snapshot ({r} rung)"
                       for r in RUNGS},
                    **{f"{r}_first": "control's own sentences, answer moved to the front"
                       for r in RUNGS}}
                d["rung_words"] = words
            else:
                d["variants"] = {c: d["variants"]["control"] for c in CONDITIONS}
            d["words"] = len(d["variants"][CONDITIONS[0]].split())
            documents.append(d)

        prompts.append({**prompt, "target_doc_id": tid,
                        "target_format": byid[tid]["format"],
                        "source_corpus": src["corpus_version"]})

    corpus = {
        "corpus_version": "length-ladder-v1",
        "intervention": "answer_first at three nested target lengths",
        "conditions": CONDITIONS, "rungs": RUNGS,
        "held_out_of_round": sorted({p["prompt_id"] for p in prompts}),
        "n_prompts": len(prompts), "n_docs": len(documents),
        "formats": sorted({d["format"] for d in documents}),
        "domains": sorted({d["domain"] for d in documents}),
        "prompts": prompts, "documents": documents,
    }
    blob = json.dumps(corpus, sort_keys=True, separators=(",", ":")).encode()
    corpus["corpus_sha256"] = hashlib.sha256(blob).hexdigest()
    out = HERE / "corpus_lengthladder.json"
    out.write_text(json.dumps(corpus, indent=2) + "\n")

    print(f"wrote {out.name}  sha256 {corpus['corpus_sha256'][:16]}")
    print(f"{len(prompts)} questions, {len(documents)} documents, "
          f"{len(CONDITIONS)} conditions\n")
    print(f"{'question':<24}{'target':<16}" + "".join(f"{r:>22}" for r in RUNGS))
    print("-" * 94)
    for pid, tkey, words, pos in report:
        print(f"{pid:<24}{tkey:<16}"
              + "".join(f"{f'{words[r]}w, answer @w{pos[r]}':>22}" for r in RUNGS))
    print("\n'answer @wN' is the word index where the answer sentence starts in the")
    print("control. Where it grows with the rung, answer_first is moving the answer")
    print("further; where it is fixed, only the document around it grows.")
    cand = [d for d in documents if not d.get("is_target")]
    print(f"\ncandidates are unchanged: {len(cand)} documents, "
          f"{min(d['words'] for d in cand)}-{max(d['words'] for d in cand)} words")


if __name__ == "__main__":
    main()
